# Generated by Django 4.2.6 on 2023-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jessi_no', models.CharField(help_text='JESSI NO', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('Team', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('Matches', models.IntegerField()),
            ],
        ),
    ]
